filebeat.inputs:
- type: container
  paths:
    - '/var/log/containers/*.log'
  processors:
    - add_kubernetes_metadata: ~

output.elasticsearch:
  hosts: ['${ELASTICSEARCH_HOSTS:elasticsearch:9200}']

logging.level: info
logging.to_files: false
logging.to_syslog: false
